import jax.numpy as jnp
from itertools import combinations, product

varnames = ['IG', 'Seq', 'Cond']

def load_infant_data():

    filename = 'data/processed_data.npz'
    data = jnp.load(filename)

    Y = data['LA_matrix']
    exposure_matrix = data['exposure_matrix']       # {0, 1}
    kl_matrix = data['kl_matrix']                   # [0, 0.08]
    sequence_matrix = data['sequence_matrix']       # [0, 1]
    condition_matrix = data['condition_matrix']     # {0, 1}

    X = jnp.stack([kl_matrix,                                                           # 0
                sequence_matrix,                                                     # 1
                condition_matrix]).transpose([1, 2, 3, 0])                                                   # 2
    
    return X, Y, exposure_matrix, varnames




# some of these helper functions to enumerate all models were generated by chatgpt

def interaction_models(features, max_order=None, include_empty=True, hierarchical=True):
    """
    Generate all models consisting of:
      - a subset of `features` as main effects
      - any combination of valid interaction effects (subsets of those mains)

    With `hierarchical=True`, any k-way interaction is only allowed if
    all its lower-order interactions (of size >= 2) built from the same
    variables are also included.

    Each model is a list:
        [main1, main2, ..., [i, j], [i, j, k], ...]
    """
    features = list(features)
    n = len(features)
    if max_order is None:
        max_order = n

    models = []
    start_r = 0 if include_empty else 1

    for r in range(start_r, n + 1):
        for mains in combinations(features, r):
            mains = list(mains)

            # All potential interaction terms for this set of mains
            inter_terms = [
                list(c)
                for order in range(2, min(max_order, len(mains)) + 1)
                for c in combinations(mains, order)
            ]

            m = len(inter_terms)

            # For each interaction, choose include/exclude (0/1)
            for mask in product([0, 1], repeat=m):
                chosen_inters = [
                    term for bit, term in zip(mask, inter_terms) if bit
                ]

                if hierarchical and chosen_inters:
                    chosen_set = {tuple(term) for term in chosen_inters}
                    valid = True
                    # Enforce: if a higher-order interaction is present,
                    # all its lower-order (>=2) subsets must also be present.
                    for term in chosen_inters:
                        if len(term) <= 2:
                            continue
                        for order in range(2, len(term)):
                            for sub in combinations(term, order):
                                if tuple(sub) not in chosen_set:
                                    valid = False
                                    break
                            if not valid:
                                break
                        if not valid:
                            break
                    if not valid:
                        continue  # skip this model

                models.append(mains + chosen_inters)

    return models

#
def build_design_matrix(X, model):
    """
    Given:
      - X: array with shape (..., D), e.g. (N, S, T, D)
      - model: list like [0, 1, 2, [0, 1], [0, 2], [1, 2], [0, 1, 2]]
    
    Returns:
      - design: array with shape (..., P) where P = #mains + #interactions
        The leading dimensions (e.g. N, S, T) are unchanged.
    """
    *batch_dims, d = X.shape   # e.g. [N, S, T], d = D

    # Separate main effects and interaction terms
    mains = [m for m in model if not isinstance(m, (list, tuple))]
    inters = [m for m in model if isinstance(m, (list, tuple))]

    cols = []

    # Add main effect "columns" (last dimension)
    for j in mains:
        # Keep dims so result has shape (..., 1)
        cols.append(X[..., j:j+1])

    # Add interaction effects as products over selected features
    for term in inters:
        idx = list(term)
        # X[..., idx] has shape (..., k); product over the last axis
        col = jnp.prod(X[..., idx], axis=-1, keepdims=True)  # (..., 1)
        cols.append(col)

    if cols:
        # Concatenate along the last axis (feature dimension)
        design = jnp.concatenate(cols, axis=-1)  # shape (..., P)
    else:
        # Null model: no columns, keep batch dims
        design = jnp.zeros(batch_dims + [0], dtype=X.dtype)

    return design

#
def index2name(models, ix):
    model = models[ix]
    name = ''
    main_effects = list(filter(lambda x: isinstance(x, int), model))
    name += ', '.join([varnames[i] for i in main_effects])

    interaction_effects = list(filter(lambda x: isinstance(x, list) and len(x)==2, model))
    if len(interaction_effects) > 0:
        name += ', '
        int_effects_string_list = []
        for int_ef in interaction_effects:
            int_effects_string_list.append(f'{varnames[int_ef[0]]}*{varnames[int_ef[1]]}')
        name += ', '.join([str(i) for i in int_effects_string_list])

    
    if [0, 1, 2] in model:
        name += ', ' + f'{varnames[0]}*{varnames[1]}*{varnames[2]}'

    if name == '':
        name = 'Null'
    return name

#
def ix2term(ix):
    if isinstance(ix, int):
        return varnames[ix]
    elif len(ix) == 2:
        return f'{varnames[ix[0]]}*{varnames[ix[1]]}'
    else:
        return f'{varnames[ix[0]]}*{varnames[ix[1]]}*{varnames[ix[2]]}'
    
#


